In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

### tensor

In [17]:
x=torch.empty(4,2)
print(x)

tensor([[8.2645e+20, 1.2915e-11],
        [2.6855e-06, 3.3057e+21],
        [4.4150e-05, 1.0335e-05],
        [3.4199e+21, 2.6950e-09]])


In [5]:
#무작위로 초기화된 텐서
x = torch.rand(4,2)
print(x)

tensor([[0.8787, 0.8250],
        [0.8589, 0.7848],
        [0.6202, 0.8849],
        [0.5196, 0.8853]])


In [6]:
#데이터 타입이 long이고, 0으로 채워진 텐서 (long이기 때문에 소수형 없이 정수형 형태)
x = torch.zeros(4,2, dtype=torch.long )
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [7]:
#사용자가 입력한 값으로 텐서 초기화
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


In [8]:
#2X4 크기, double타입, 1로 채워진 텐서
x = x.new_ones(2,4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [9]:
# x와 같은 크기, float 타입, 무작위로 채워진 텐서
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.2800, -1.0084,  0.6670,  0.8920],
        [-1.1303,  0.8352,  1.2674,  0.1286]])


In [10]:
#텐서의 크기 계산
print(x.size())

torch.Size([2, 4])


### 데이터 타입

In [12]:
ft = torch.FloatTensor([1,2,3]) #기본이 32
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [13]:
print(ft.short()) # 캐스팅
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [15]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [16]:
print(it.float()) #일반은 32bit 였음
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


### CUDA Tensors
- .to 메소드를 이용해 텐서를 어떠한 장치(CPU, GPU)로도 옮길 수 있음

In [20]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.4489])
0.4489488899707794
torch.float32


In [23]:
#디바이스를 정의
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y=torch.ones_like(x, device=device)
print(y)

cpu
tensor([1.])


### 다차원 텐서 표현

0D Tensor(Scalar)
- 하나의 숫자를 담고 있는 텐서(tensor)
- 축과 형상이 없음

In [24]:
t0 = torch.tensor(0)
print(t0.ndim) # dimension
print(t0.shape)
print(t0) # 실제값

0
torch.Size([])
tensor(0)


1D Tensor(Vector)
- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [26]:
t1 = torch.tensor([1,2,3])
print(t1.ndim) # dimension
print(t1.shape)
print(t1) # 실제값

1
torch.Size([3])
tensor([1, 2, 3])


2D Tensor(Matrix)
- 행렬과 같은 모양으로 두 개의 축이 존재
- 일반적인 수치, 통계 데이터셋이 해당
- 주로 샘플과 특성을 가진 구조로 사용함